### ISSUE TITLE
Should ToS & Privacy be in Git or is Google Docs OK?

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#1]
I'm on the fence. For legal reasons it's important that we keep track of what was published when. Since we aren't publishing from Git, tracking changes here doesn't completely solve the problem. I will happily maintain in either place. Answer for now should depend on convenience since none of us has any spare time.

Thoughts?

**Comment by mostarz93** [comment]
I dont see anything wrong with google docs at the moment

**Comment by murphy** [comment]
Cool, we'll leave it there then for now.  @newtectonics if you agree, please close this.

**Comment by newtectonics** [comment]
I agree. GDocs has all the history we need.
