### ISSUE TITLE
Button text not centered vertically

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#105]
eg
<img width="149" alt="Screen Shot 2021-11-24 at 14 43 33" src="https://user-images.githubusercontent.com/6160738/143249629-eef8f8da-ccb2-4b31-ab90-16256ee2f328.png">
:
<img width="96" alt="Screen Shot 2021-11-24 at 14 43 38" src="https://user-images.githubusercontent.com/6160738/143249632-9a149c4a-8530-4961-8a27-c393280d6f4d.png">

**Comment by elektramurphy** [comment]
@murphy this is from the font - they have the exact same top and bottom spacing

**Comment by murphy** [comment]
@elektramurphy Can you switch those to Roboto too please?
