### ISSUE TITLE
Risk Platform description

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#110]
A risk ecosystem powered by reliable data, original research, and an engaged community reducing risk for everyone.

Manage risk exposure

Visualize risk metrics

**Comment by elektramurphy** [comment]
@murphy how do you want these two structured? Can't just have them like that

Manage risk exposure

Visualize risk metrics

**Comment by murphy** [comment]
Sorry for not being clear. Those are meant to be new descriptions under Mark's drawings.

**Comment by murphy** [comment]
In the pink box under "What is Credmark".
