### ISSUE TITLE
"How it Works" diagram

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#112]
I think this diagram needs some graphic design work. (Does Mark not have access to repo?)...It's a bit ugly. 

* I don't like the writing on the left-hand arrows. In fact it's probably unnecessary.
* Instead of "Raw Blockchain Data" you might want to say "Data Curators" since the other two boxes in that column contain the actors. Then, in the "Data Platform" box you could write "Indexed enhanced blockchain data"

**Comment by elektramurphy** [comment]
@murphy I'll find out if he has an account so we can tag him

**Comment by elektramurphy** [comment]
@markvalentine do you have an ETA for this graphic?
