### ISSUE TITLE
DeFi Data Section

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#115]
DeFi Data for DeFi Applications

Credmark's data is pulled from the blockchain, curated, indexed, and then made accessible via APIs for DeFi application builders. Credmark uses its own data to produce its risk dashboard.

Documentation

See how to use the API.

"View API"....will we actually have something to link to or does Mark need to design a "Coming Soon" page?

**Comment by elektramurphy** [comment]
@murphy we decided to cut this section until other stuff it released - should we added again in the next couple of weeks
