### ISSUE TITLE
Learn More About Credmark

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#117]
This section is weird. 

* "Documentation" links to reports. 
* I don't think "Get in Touch" belongs there.
* And "Newsletter" doesn't let you signeup!

I'd like to see:

* FAQ
* Reports
* Blog
* Signup for our Newsletter

**Comment by murphy** [comment]
Actually, whatever you put should parallel what you have in the "Learn" section of the footer.

**Comment by elektramurphy** [comment]
@murphy where do you want documentation linking to ?

**Comment by elektramurphy** [comment]
<img width="1435" alt="Screenshot 2021-11-24 at 18 14 23" src="https://user-images.githubusercontent.com/57063146/143292886-c3a55b1f-1ba2-4f42-89f8-7692338726b3.png">

Not sure about this from a design POV
