### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#118]
Projects
* Risk Library
* Reports
* Risk Dashboard (app.credmark.com)

Learn
👍🏻...but Documentation needs to point to documentation...for now I think we need to leave it out because we don't actually have any documentation.

**Comment by elektramurphy** [comment]
I'm gonna update documentation in the footer to reports and point it to the reports page. @wcsu95 let me know if you're happy with this.

**Comment by wcsu95** [comment]
@elektramurphy How about white paper?
I don't think any of the links point to the white paper.

@murphy 
Is the risk dashboard going to be on the same domain as smartpool?

**Comment by elektramurphy** [comment]
@wcsu95 Ok - will point to the white paper

**Comment by murphy** [comment]
@elektramurphy the dashboard will be at app.credmark.com and SmartPool will move to smartpool.credmark.com
