### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#119]
If we're going to title this page "Contributors", the URL should be /contributors and all the text linking to this page should be "Contributors", not "Team"

We have to fix the "|" Between the name and the title. The way it breaks always makes it look like a "I", as in "I", "II", "III", "IV". Find another way to display this data. Probably name and title should be in different font sizes and/or weights. This is a design issue I realize. 

If we're going to go with the notion of contributors, we should just state what they are responsible for, not their title. Please change to:

* Neil: Vision & Product
* Momin: Marketing
* Paul: Operations
* Emilie: Engineering
* Asan: Risk
* Nish: Data Science
* Collier: Operation
* Stijn: Design
* Joey: Data
* Wen-Chiao: Community

The way the toggle between "Core Team" and "Advisors" works is silly. When you click on "Core Team" you get both and when you click on "Advisors" you get advisors! Please create:

* All
* Core Contributors
* Adivisors

and setup toggles accordingly.

Advisors should also have their specialty associated with them.

* Renan: Security
* Jonah: Product
* Heikki: Vision
* Alberto: Engineering
* Serge: Strategy

**Comment by elektramurphy** [comment]
<img width="962" alt="Screenshot 2021-11-24 at 18 28 23" src="https://user-images.githubusercontent.com/57063146/143294667-822d703d-4d9d-4b3b-a347-62c9f756c064.png">

**Comment by elektramurphy** [comment]
@wcsu95 @murphy for the launch we'll go no filter for team page - it's a bit more complicated with these different components and I'm squeezed on time. Will role out asap so keep this issue open.
