### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#123]
I don't like the fact that one of our 3 top menu items is just a link to our Discord, which is already accessible from the footer. 

I also think it's goofy that our "Community" section in the footer has a "Community" item. I think the Community section should read:

* Contributors
* Work with us
* Our Discord

**Comment by wcsu95** [comment]
I don't know what the site looks like at the moment, but the intention would be to link to discord and other social media outlet via these icons.

**Comment by murphy** [comment]
@elektramurphy can you do a screen share with @wcsu95 so he has some context?
