### ISSUE TITLE
What is this section doing in the admin?...seems to have no effect

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#13]
![image](https://user-images.githubusercontent.com/6160738/51084081-981fe780-1724-11e9-8409-cb0894221f43.png)

**Comment by mostarz93** [comment]
Its for different sized screens. There are lots of these 'hidden' sections if you are in the website builder. Messing with any of that will cause massive problems

**Comment by murphy** [comment]
GTK, but sad. I'll try to make sure I always update both sections.
