### ISSUE TITLE
Research --> Risk Library

### ISSUE THREAD

**Issue by mostarz93** [credmark/credmark-website-v1#136]
The first blue graphic box should say "Risk Library" not Research

2nd blue box, outer text should say "Research" like it currently does,  but there should only be 1 inner white box that says Risk Library

**Comment by wcsu95** [comment]
@mostar93 
![image](https://user-images.githubusercontent.com/89830616/144987618-1c5b9546-1d9b-4df9-b591-f20cff09d7c9.png)
Do you mean to remove both commissioned reports/historical reports and to only keep risk library?

**Comment by mostarz93** [comment]
yes

**Comment by wcsu95** [comment]
@markvalentine We decided to remove both "commissioned/historical reports" in the research section as shown in the photo attached below.
Can you help readjust the dimensions, or any ideas to help polish it up is highly appreciated.
Thanks!
![Graph 2](https://user-images.githubusercontent.com/89830616/144998270-4d14a6ff-cbe0-46ff-87b4-1007086957f6.png)
