### ISSUE TITLE
Smartpool CTA button

### ISSUE THREAD

**Issue by mostarz93** [credmark/credmark-website-v1#137]
Should say "Try Smartpool"

Also, APP at the top needs to go to the to be released Risk Terminal

Smartpool needs to be understated until we know what we're doing with it

**Comment by elektramurphy** [comment]
I updated the CTA button - what link do you want the APP button to go to ?

**Comment by mostarz93** [comment]
for now smartpool. But whenever the risk terminal has a proper dns, it should be tht

**Comment by elektramurphy** [comment]
Ok so I should update to: https://app.credmark.com/positions

**Comment by elektramurphy** [comment]
Also, since you said this should be understated, should we just remove this whole section from the homepage for now? @mostar93

**Comment by elektramurphy** [comment]
<img width="1440" alt="Screenshot 2021-12-07 at 08 11 11" src="https://user-images.githubusercontent.com/57063146/144991085-d2b2fdae-4ae5-4a02-97bf-fc65eec5370e.png">

**Comment by mostarz93** [comment]
yeah sure, ditch it
