### ISSUE TITLE
Uncovering DeFi risks

### ISSUE THREAD

**Issue by wcsu95** [credmark/credmark-website-v1#139]
@murphy @elektramurphy 
Since we removed the reports module from the home page, I'm going to propose to remove this header as this was supposed to be a high level overview of what's going to be at the bottom; ex: reports & risk library. 

![image](https://user-images.githubusercontent.com/89830616/145193736-bfd5f804-05eb-495a-87a6-4b495eda9824.png)

**Comment by elektramurphy** [comment]
@wcsu95 is this something we still want to remove?
