### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#147]
Under **Project**:

* "Documentation" should be "Whitepaper"
* Add "Risk Library"
* "Crypto Data" should be "Reports"
* "Risk Management Tools" should be "Risk Terminal"

All of those should open another tab since we're leaving the main Credmark site.

**Comment by elektramurphy** [comment]
@murphy Momin wants to hide the reports in the footer - should I just remove Reports?

**Comment by murphy** [comment]
Just talked to Momin.

We are going to have a "Reports" link, which will point to the current page. We are going to make some small changes to the current page:

1. Title will be "Reports"
2. The first thing will be new reports. So far we have one report. 
3. Under that we'll have a sub-section called "Historical Reports" where we'll put all the CCRs. We'll have to include some verbiage that puts them in context. I'm happy to provide that.

**Comment by elektramurphy** [comment]
@murphy can I add the risk library as the current report ?

**Comment by murphy** [comment]
No. We have a report for Coinshift. Ask Collier for a PDF version you can use.
