### ISSUE TITLE
Add blog

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#151]
https://docs.google.com/document/d/1AbqKPMfmS7ug_TOtomLVmDpA1f3drq8BxO-Zr-Qc6Po/edit?usp=sharing

**Comment by elektramurphy** [comment]
@murphy is this blog live on medium ? I can't find it.

**Comment by murphy** [comment]
I don't think so.

**Comment by elektramurphy** [comment]
@murphy you need to get Stijn to give you images for it.

**Comment by murphy** [comment]
Have dropped him a ref in Discord.
