### ISSUE TITLE
FAQ SEO

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#17]
I think the answer is 'yes', but I want to be sure.

Is the way we have FAQ answers in hidden divs SEO-friendly?

**Comment by mostarz93** [comment]
damn, did some research and this might be an issue

**Comment by murphy** [comment]
OK, let's fix that, even if it's less elegant.

**Comment by mostarz93** [comment]
changed this. let me know if its ok or not. I really miss the hidden divs :'(

**Comment by murphy** [comment]
I miss the hidden divs too!  

I find the 2 columns hard to read.  

I wonder if it shouldn't be a really long page with the questions at the top.  When you click on one, you jump down to the question with the answer.  I've seen that before. I always thought it was weird, but I guess it's for SEO.

**Comment by mostarz93** [comment]
Yeah that does seem weird. But its probably better than what I have right now
