### ISSUE TITLE
Monthly Update signup page

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#19]
This isn't directly related to the web site, but since we need to style the newsletter signup page, might as well do this one too.

Thanks.

**Comment by mostarz93** [comment]
Not sure where exactly this is?

**Comment by murphy** [comment]
* Log into Mailchimp

* Click on Audience

* Click on Signup forms

**Comment by elektramurphy** [comment]
@murphy @mostar93 I made one via mailchimp for the new website. It pops up in a new tab when you click subscribe on the blog page (you'll see when the website is live). Can I close this issue?
