### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#20]
Let's add it. 

You mentioned needing a plug-in. I'm surprised. Should just be a few lines of JS added to each page.

**Comment by mostarz93** [comment]
Should be good to go. Both of yall should have received invites to the google analytics page

**Comment by murphy** [comment]
Is this active? Have you tested it?  I don't see anything.

**Comment by mostarz93** [comment]
It definitely recognized that I was using the site

**Comment by mostarz93** [comment]
It tracks previous day use as well as real time. Ill know more tomorrow. But you should visit the site a few times

**Comment by murphy** [comment]
The problem was 100% mine.  I finally realized what it was when I was staring at the JS on the home page wondering why it wasn't working.  I use Brave, which stops all trackers.  Sooooo, not seeing anything was my fault. I tested with Opera and Safari and it worked perfectly.

Thanks.
