### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#21]
I think it's time to make all the search engines aware of our site. There are lots of tools to do this, although I have no idea what the state of the art is.  

(@newtectonics for visibility)

**Comment by mostarz93** [comment]
Installed Yoast SEO on the site. Should help a lot with this.

**Comment by murphy** [comment]
Please check to make sure they submit site to search engines.

**Comment by mostarz93** [comment]
like 90% there. we're good to go with Bing and Google. Just ironing out a few web caching details and some image optimization for speed

**Comment by mostarz93** [comment]
this should be good to close

**Comment by murphy** [comment]
No obvious way to check it so I'll trust you 😉
