### ISSUE TITLE
Need a media page 

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#33]
Please link & preview any articles related to the demo days, whether or not we were mentioned.

Thx.

**Comment by mostarz93** [comment]
https://graychain.net/media/

Should we add a press@graychain.net as well and include that on this page? Maybe a short bio/tagline to make it easy for inquiring press people?

**Comment by murphy** [comment]
For sure.

**Comment by mostarz93** [comment]
any ideas for a good press quote that I can put on this page? Also, its up to date with every bit of press that Zeroth got, which as you pointed out on slack has been minimal... Let me know if you think of any other type articles or press we can link to. Ill do the same

**Comment by murphy** [comment]
Hmmm, you have things on our page that aren't in the spreadsheet.  Can you please sync them up:  https://docs.google.com/spreadsheets/d/1XD_4xzzRggjk2_LCNLDrHW-va1wiD7CtON_f6QeO08o/edit#gid=816992343

**Comment by murphy** [comment]
Articles should open in another tab.

**Comment by murphy** [comment]
re: a quote...how about:

"I can describe Graychain in one word: ambitious!"

It's not an actual quote, but who's going to check?

**Comment by mostarz93** [comment]
this should be good to close, but give it another look! 

https://graychain.net/media/

**Comment by murphy** [comment]
Still some problems with it.  One article goes to _trashed and another opens in the same tab.

**Comment by mostarz93** [comment]
try clearing your cache

**Comment by murphy** [comment]
👍🏻
