### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#34]
@mostar93 

https://graychain.net/careers/back-end-developer/ doesn't mention that the job is based in Bangkok. Need to add that since it's out of the JobsDB context.

@newtectonics 

Do we need front-end now?  

In either case, can you please write up job desc for data engineer and, if necessary, front-end?  I'm sending people to our jobs page and I want them to have as much info as possible.

Thanks!

**Comment by mostarz93** [comment]
I need a list of benefits for these descriptions as well

**Comment by mostarz93** [comment]
I dont have copy for any of the other 2 positions (front end and data-engineer). But im also not sure if this is still a super high priority?

**Comment by murphy** [comment]
We should add them.  Job openings are a proxy for "the company is growing".  If Neil doesn't have time to write them, steal descriptions from another site and massage it to look like one of ours.

Thx

**Comment by mostarz93** [comment]
These are ready for review:

https://graychain.net/careers/front-end-developer/
https://graychain.net/careers/data-engineer/

Wasnt sure if I should make living/relocating to Bangkok a requirement. Also, are we looking for folks who are proficient with Blockchain tech?

**Comment by murphy** [comment]
Bangkok not a requirement.  Blockchain tech not a requirement.

These are good.

Thank you!

**Comment by mostarz93** [comment]
good to close for now?
