### ISSUE TITLE
Partners » Partners & Investors

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#39]
Was just looking at [Utu](https://utu.io) site.  They have a section called "Partners & Investors" which allows them to include Animoca and Artesian.  I think that's clever and think we should do same.  

If you agree, please hand this over to Momin.

**Comment by mostarz93** [comment]
Let me know if im missing any or included someone i shouldn't. Are we including folks that have signed LOI??

Zeroth
Google Cloud
Okta
Animoca 
Artesian
D5
Ethereum
Digital Ocean
AWS (not sure about this one)

**Comment by murphy** [comment]
We are officially using AWS, so might as well include them. 

And yea, once we have signed LOIs from partners, we'll include them.  Pretty sure Dapp.com ( http://dapp.com/ )  will be back.

- P

**Comment by mostarz93** [comment]
this has been updated: 

https://graychain.net/our-story/

**Comment by murphy** [comment]
Hot!
