### ISSUE TITLE
blog page

### ISSUE THREAD

**Issue by mostarz93** [credmark/credmark-website-v1#42]

**Comment by mostarz93** [comment]
https://graychain.net/blog/

link to this is in the footer now

**Comment by murphy** [comment]
Great, but shouldn't that link be under Follow Us?

**Comment by mostarz93** [comment]
I guess my thought was that the blog is part of explaining our mission. But i can move it you feel differently

**Comment by murphy** [comment]
Most people seem to put it under "Follow us" so I think we should just follow the convention.  Thanks.

**Comment by mostarz93** [comment]
done!

**Comment by murphy** [comment]
Thanks!
