### ISSUE TITLE
Time to re-design the about us section

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#46]
Hi Momin -

We need to re-design the section with bios.  We're going to put everyone on it, in alphabetical order.  Each one should be more discrete (hard to be less discrete 😄) and the bios will be shorter.  One issue is that we need all of the photos to be similar even though they won't be similar to start with. That's your challenge. 

Start off by adding yourself, Robert, and Laura.

We'll soon be adding George, maybe Scott, maybe Emily (Neil is supposed to confirm), Serge, and then maybe Wen-Chiao.  

Thanks!

- Paul

**Comment by mostarz93** [comment]
do you have pictures for Robert and Laura? or emails so i can reach out to them?

**Comment by murphy** [comment]
Probably best to reach out to them.  Robert has a photo on LinkedIn but don't know if that's what he wants us to use.

robert@graychain.net

laura@graychain.net

Please ask them for short bios that we can edit down.

Thx

**Comment by mostarz93** [comment]
Take a look, lemme know what you think!

https://graychain.net/about-us/

**Comment by murphy** [comment]
I like it, although I'm wondering about something I'll talk to Neil about in a couple of hours.  IOW, not quite signing off 🙂

**Comment by murphy** [comment]
In case Neil didn't tell you, we're happy with what you've done.  You can publish it!

**Comment by mostarz93** [comment]
done!

**Comment by mostarz93** [comment]
Asahi has been added

**Comment by murphy** [comment]
I saw that!  2 more soon.  Please don't forget to alphabetize entries.  Thanks!
