### ISSUE TITLE
Contact us email ... bot prevention

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#5]
Please add an "I am not a robot" switch.

**Comment by mostarz93** [comment]
Added reCAPTCHA v3 to the contact form. The interwebs say this is the best way to do it

**Comment by murphy** [comment]
Is this deployed?  I see the "Protected by captcha" widget, but no actual protection.

**Comment by mostarz93** [comment]
version 3 doesnt require any sort of checkbox or anything.

**Comment by mostarz93** [comment]
https://stackoverflow.com/questions/51171349/how-does-googles-recaptcha-v3-work

**Comment by murphy** [comment]
Sweet.  Thanks.
