### ISSUE TITLE
Links to Coindesk and The Block articles

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#53]
Shouldn't those be appearing on our front page?

**Comment by mostarz93** [comment]
Typically, ive reserved the front page for our own blog posts and i keep our 3rd party press in the 'Media' section.  Im happy to make an exception in this case if you'd like.

**Comment by murphy** [comment]
Separating media & blog makes total sense.  I just assumed you combined them because when I checked the blog link I saw media articles in there!  Also, I though that the three articles on the front pager were automatically the last three articles in the blog section.  

So I'm still  confused. 

I like the strict separation (in which case you have cleanup to do in the blog section) but then how do you decide what gets promoted to the front page?  

Also, I didn't see the Media link because I didn't expect it to be under "Get Started".

**Comment by mostarz93** [comment]
The front page, generally speaking, should be stuff that we produce, but i think being mentioned by someone like Coindesk warrants front page placement.

I will clean up the blog. You are right, it should be separate.

And I always thought 'getting started' implied how to begin to work with us via careers, press/media or just through the contact form, but i guess its not as clear as i thought

**Comment by murphy** [comment]
Cool

**Comment by murphy** [comment]
And agree.

**Comment by mostarz93** [comment]
how about changing "getting started" to "work with us"   ?

**Comment by murphy** [comment]
Went through this with Neil this morning. This is what we'd like to do:

* Move "Media" to the bottom of "Follow us"

* Move "Careers" and "Contact Us" to the bottom of "About us"

* Nuke "Getting Started"

Thanks!

- Paul

**Comment by mostarz93** [comment]
Cool, take a look!

**Comment by murphy** [comment]
😂

You and your icons.

You do realize that you put an "RSS feed" icon in front of "Blog" (and AFAIK we haven't setup an RSS feed for it) and a "Text" icon in front of media.  Believe it or not, most people still get their news from newspapers (hard copy or digital), not from texts!  

I don't mind though. I think the icons give us Millennial cred, even if they're wrong.  I say this from the perspective of a generation that gave the world a floppy-disk icon for "Save". I think we still owe you for that one.

- P
