### ISSUE TITLE
New section for reports

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#54]
We need a new section for the industry reports.

It should be a new link in the footer under "Our Mission". The link should be "The Industry".

That should link to a landing page that describes what the report is about and then links to all of the reports published to date.

**Comment by mostarz93** [comment]
Currently i have it linked directly to the first report. I was planning on making a landing page with a blurb once the second report comes out

**Comment by mostarz93** [comment]
Actually...looks like i havent published that change quite yet. Ill do that shorlty

**Comment by murphy** [comment]
K. Let me know

**Comment by mostarz93** [comment]
Ok should be good to go.

**Comment by murphy** [comment]
It is. Thank you!

- Paul
