### ISSUE TITLE
Contact us email nav bar

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website-v1#7]
Is there any reason the "Contact us" nav bar isn't consistent with the home page?

**Comment by mostarz93** [comment]
Can you send screenshot for clarity?

**Comment by murphy** [comment]
Standard nav bar:

![image](https://user-images.githubusercontent.com/6160738/51126494-95f08280-1823-11e9-88cc-7ca0f7c549fa.png)

Contact us nav bar:

![image](https://user-images.githubusercontent.com/6160738/51126520-adc80680-1823-11e9-9d0c-20cc92f6b007.png)

Kind of different 😉

**Comment by mostarz93** [comment]
ahh yes,
